version: '3.8'

services:
  db:
    image: postgres:15-alpine  # Use a specific, lightweight postgres image
    container_name: my_project_db
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - '5430:5432' # Map your local port 5432 to the container's port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: # This ensures your data persists even if the container is removed